# -*- coding: utf-8 -*-
"""Homework_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qfy1XQ4EEjC2VyypgtAgoFKw8sWvX_S5

# Задача 44.
В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего
из 1 столбца.

Ваша задача перевести его в one hot вид.

Сможете ли вы это сделать без
get_dummies?

```
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()
```
"""

import pandas as pd
import random

lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'who_am_I': lst})
data.head()

data.loc[data['who_am_I'] == 'robot', 'robot'] = '1'
data.loc[data['who_am_I'] != 'robot', 'robot'] = '0'
data.loc[data['who_am_I'] == 'human', 'human'] = '1'
data.loc[data['who_am_I'] != 'human', 'human'] = '0'
data.drop('who_am_I', axis=1, inplace=True)
print(data)
